---
- name: Install and configure Jenkins controller
  hosts: jenkins
  become: true

  tasks:
    - name: Update packages
      dnf:
        name: "*"
        state: latest

    - name: Install core packages
      dnf:
        name:
          - git
          - unzip
          - tar
          - wget
          - jq
          - docker
          - java-17-amazon-corretto
        state: present

    - name: Add Jenkins repo
      get_url:
        url: https://pkg.jenkins.io/redhat-stable/jenkins.repo
        dest: /etc/yum.repos.d/jenkins.repo
        mode: '0644'

    - name: Import Jenkins signing key
      rpm_key:
        state: present
        key: https://pkg.jenkins.io/redhat-stable/jenkins.io-2023.key

    - name: Install Jenkins
      dnf:
        name: jenkins
        state: present

    - name: Start and enable Docker
      service:
        name: docker
        state: started
        enabled: true

    - name: Add jenkins user to docker group
      user:
        name: jenkins
        groups: docker
        append: true

    - name: Download AWS CLI zip
      get_url:
        url: https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip
        dest: /tmp/awscliv2.zip
        mode: '0644'

    - name: Unzip AWS CLI
      unarchive:
        src: /tmp/awscliv2.zip
        dest: /tmp/
        remote_src: true

    - name: Install AWS CLI
      command: /tmp/aws/install --update

    - name: Install kubectl
      get_url:
        url: https://dl.k8s.io/release/v1.33.1/bin/linux/amd64/kubectl
        dest: /usr/local/bin/kubectl
        mode: '0755'

    - name: Install Terraform
      unarchive:
        src: https://releases.hashicorp.com/terraform/1.12.2/terraform_1.12.2_linux_amd64.zip
        dest: /usr/local/bin/
        remote_src: true

    - name: Install Helm
      shell: curl -fsSL https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
      args:
        creates: /usr/local/bin/helm

    - name: Install Ansible
      dnf:
        name: ansible-core
        state: present

    - name: Start and enable Jenkins
      service:
        name: jenkins
        state: started
        enabled: true
