apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: home-service-ingress
  namespace: home-service
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/group.name: home-service
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80}]'
spec:
  ingressClassName: alb
  rules:
    - host: api.YOUR_DOMAIN
      http:
        paths:
          - path: /users
            pathType: Prefix
            backend:
              service:
                name: user-service
                port:
                  number: 80
          - path: /bookings
            pathType: Prefix
            backend:
              service:
                name: booking-service
                port:
                  number: 80
          - path: /workers
            pathType: Prefix
            backend:
              service:
                name: worker-service
                port:
                  number: 80
